name: 🚀 Deployment (CI)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "development"
        type: choice
        options:
          - development
          - staging
          - production

permissions:
  contents: write # needed to push tags and release assets
  issues: write # needed to comment on issues
  pull-requests: write # needed to comment on PRs

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.21.1"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set environment
        id: env
        run: echo "env=${{ inputs.environment }}" >> $GITHUB_OUTPUT

      - name: EAS Update
        run: yarn eas update --channel ${{ steps.env.outputs.env }} --message "$(git log -1 --pretty=%B)"

      - name: EAS Build (native binary)
        run: yarn eas build --platform android --profile ${{ steps.env.outputs.env }} --non-interactive
      - name: Semantic Release
        run: npx semantic-release
